#include "barrier_invariants_autogenerated_definitions.h"

#if defined(__1D_WORK_GROUP) || defined(__1D_THREAD_BLOCK)

#define __read_permission(X) \
    { \
        void* volatile __read_permission_temp = (void*)X;       \
    }

#endif
