/* MACHINE GENERATED - do not edit this file */
#undef __barrier_invariant_0
#undef __barrier_invariant_1
#undef __barrier_invariant_2
#undef __barrier_invariant_3
#undef __barrier_invariant_4
#undef __barrier_invariant_5
#undef __barrier_invariant_6
#undef __barrier_invariant_7
#undef __barrier_invariant_8
#undef __barrier_invariant_9
#undef __barrier_invariant_10
#undef __barrier_invariant_11
#undef __barrier_invariant_12
#undef __barrier_invariant_13
#undef __barrier_invariant_14
#undef __barrier_invariant_15
#undef __barrier_invariant_16
#undef __barrier_invariant_17
#undef __barrier_invariant_18
#undef __barrier_invariant_19
#undef __barrier_invariant_20
#undef __barrier_invariant_binary_0
#undef __barrier_invariant_binary_1
#undef __barrier_invariant_binary_2
#undef __barrier_invariant_binary_3
#undef __barrier_invariant_binary_4
#undef __barrier_invariant_binary_5
#undef __barrier_invariant_binary_6
#undef __barrier_invariant_binary_7
#undef __barrier_invariant_binary_8
#undef __barrier_invariant_binary_9
#undef __barrier_invariant_binary_10
#undef __barrier_invariant_binary_11
#undef __barrier_invariant_binary_12
#undef __barrier_invariant_binary_13
#undef __barrier_invariant_binary_14
#undef __barrier_invariant_binary_15
#undef __barrier_invariant_binary_16
#undef __barrier_invariant_binary_17
#undef __barrier_invariant_binary_18
#undef __barrier_invariant_binary_19
#undef __barrier_invariant_binary_20

#define __barrier_invariant_0(X) __NOP
#define __barrier_invariant_1(X, I0) __NOP
#define __barrier_invariant_2(X, I0, I1) __NOP
#define __barrier_invariant_3(X, I0, I1, I2) __NOP
#define __barrier_invariant_4(X, I0, I1, I2, I3) __NOP
#define __barrier_invariant_5(X, I0, I1, I2, I3, I4) __NOP
#define __barrier_invariant_6(X, I0, I1, I2, I3, I4, I5) __NOP
#define __barrier_invariant_7(X, I0, I1, I2, I3, I4, I5, I6) __NOP
#define __barrier_invariant_8(X, I0, I1, I2, I3, I4, I5, I6, I7) __NOP
#define __barrier_invariant_9(X, I0, I1, I2, I3, I4, I5, I6, I7, I8) __NOP
#define __barrier_invariant_10(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9) __NOP
#define __barrier_invariant_11(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10) __NOP
#define __barrier_invariant_12(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11) __NOP
#define __barrier_invariant_13(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12) __NOP
#define __barrier_invariant_14(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13) __NOP
#define __barrier_invariant_15(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14) __NOP
#define __barrier_invariant_16(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15) __NOP
#define __barrier_invariant_17(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16) __NOP
#define __barrier_invariant_18(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, I17) __NOP
#define __barrier_invariant_19(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, I17, I18) __NOP
#define __barrier_invariant_20(X, I0, I1, I2, I3, I4, I5, I6, I7, I8, I9, I10, I11, I12, I13, I14, I15, I16, I17, I18, I19) __NOP
#define __barrier_invariant_binary_0(X) __NOP
#define __barrier_invariant_binary_1(X, I0_0, I0_1) __NOP
#define __barrier_invariant_binary_2(X, I0_0, I0_1, I1_0, I1_1) __NOP
#define __barrier_invariant_binary_3(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1) __NOP
#define __barrier_invariant_binary_4(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1) __NOP
#define __barrier_invariant_binary_5(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1) __NOP
#define __barrier_invariant_binary_6(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1) __NOP
#define __barrier_invariant_binary_7(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1) __NOP
#define __barrier_invariant_binary_8(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1) __NOP
#define __barrier_invariant_binary_9(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1) __NOP
#define __barrier_invariant_binary_10(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1) __NOP
#define __barrier_invariant_binary_11(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1) __NOP
#define __barrier_invariant_binary_12(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1) __NOP
#define __barrier_invariant_binary_13(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1) __NOP
#define __barrier_invariant_binary_14(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1) __NOP
#define __barrier_invariant_binary_15(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1, I14_0, I14_1) __NOP
#define __barrier_invariant_binary_16(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1, I14_0, I14_1, I15_0, I15_1) __NOP
#define __barrier_invariant_binary_17(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1, I14_0, I14_1, I15_0, I15_1, I16_0, I16_1) __NOP
#define __barrier_invariant_binary_18(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1, I14_0, I14_1, I15_0, I15_1, I16_0, I16_1, I17_0, I17_1) __NOP
#define __barrier_invariant_binary_19(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1, I14_0, I14_1, I15_0, I15_1, I16_0, I16_1, I17_0, I17_1, I18_0, I18_1) __NOP
#define __barrier_invariant_binary_20(X, I0_0, I0_1, I1_0, I1_1, I2_0, I2_1, I3_0, I3_1, I4_0, I4_1, I5_0, I5_1, I6_0, I6_1, I7_0, I7_1, I8_0, I8_1, I9_0, I9_1, I10_0, I10_1, I11_0, I11_1, I12_0, I12_1, I13_0, I13_1, I14_0, I14_1, I15_0, I15_1, I16_0, I16_1, I17_0, I17_1, I18_0, I18_1, I19_0, I19_1) __NOP
