/* MACHINE GENERATED - do not edit this file */

_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_1(
  unsigned char v0
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_2(
  unsigned char v0,
  unsigned char v1
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_3(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_4(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_5(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_6(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_7(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_8(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_9(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_10(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_11(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_12(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_13(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_14(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_15(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_16(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_17(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_18(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16,
  unsigned char v17
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_19(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16,
  unsigned char v17,
  unsigned char v18
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_char_20(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16,
  unsigned char v17,
  unsigned char v18,
  unsigned char v19
);
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0
) { return __add_noovfl_unsigned_char_1(
    v0
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1
) { return __add_noovfl_unsigned_char_2(
    v0,
    v1
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2
) { return __add_noovfl_unsigned_char_3(
    v0,
    v1,
    v2
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3
) { return __add_noovfl_unsigned_char_4(
    v0,
    v1,
    v2,
    v3
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4
) { return __add_noovfl_unsigned_char_5(
    v0,
    v1,
    v2,
    v3,
    v4
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5
) { return __add_noovfl_unsigned_char_6(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6
) { return __add_noovfl_unsigned_char_7(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7
) { return __add_noovfl_unsigned_char_8(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8
) { return __add_noovfl_unsigned_char_9(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9
) { return __add_noovfl_unsigned_char_10(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10
) { return __add_noovfl_unsigned_char_11(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11
) { return __add_noovfl_unsigned_char_12(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12
) { return __add_noovfl_unsigned_char_13(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13
) { return __add_noovfl_unsigned_char_14(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14
) { return __add_noovfl_unsigned_char_15(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15
) { return __add_noovfl_unsigned_char_16(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16
) { return __add_noovfl_unsigned_char_17(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16,
  unsigned char v17
) { return __add_noovfl_unsigned_char_18(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16,
  unsigned char v17,
  unsigned char v18
) { return __add_noovfl_unsigned_char_19(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned char v0,
  unsigned char v1,
  unsigned char v2,
  unsigned char v3,
  unsigned char v4,
  unsigned char v5,
  unsigned char v6,
  unsigned char v7,
  unsigned char v8,
  unsigned char v9,
  unsigned char v10,
  unsigned char v11,
  unsigned char v12,
  unsigned char v13,
  unsigned char v14,
  unsigned char v15,
  unsigned char v16,
  unsigned char v17,
  unsigned char v18,
  unsigned char v19
) { return __add_noovfl_unsigned_char_20(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18,
    v19
    );
}
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_1(
  unsigned short v0
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_2(
  unsigned short v0,
  unsigned short v1
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_3(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_4(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_5(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_6(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_7(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_8(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_9(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_10(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_11(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_12(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_13(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_14(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_15(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_16(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_17(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_18(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16,
  unsigned short v17
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_19(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16,
  unsigned short v17,
  unsigned short v18
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_short_20(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16,
  unsigned short v17,
  unsigned short v18,
  unsigned short v19
);
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0
) { return __add_noovfl_unsigned_short_1(
    v0
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1
) { return __add_noovfl_unsigned_short_2(
    v0,
    v1
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2
) { return __add_noovfl_unsigned_short_3(
    v0,
    v1,
    v2
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3
) { return __add_noovfl_unsigned_short_4(
    v0,
    v1,
    v2,
    v3
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4
) { return __add_noovfl_unsigned_short_5(
    v0,
    v1,
    v2,
    v3,
    v4
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5
) { return __add_noovfl_unsigned_short_6(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6
) { return __add_noovfl_unsigned_short_7(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7
) { return __add_noovfl_unsigned_short_8(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8
) { return __add_noovfl_unsigned_short_9(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9
) { return __add_noovfl_unsigned_short_10(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10
) { return __add_noovfl_unsigned_short_11(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11
) { return __add_noovfl_unsigned_short_12(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12
) { return __add_noovfl_unsigned_short_13(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13
) { return __add_noovfl_unsigned_short_14(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14
) { return __add_noovfl_unsigned_short_15(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15
) { return __add_noovfl_unsigned_short_16(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16
) { return __add_noovfl_unsigned_short_17(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16,
  unsigned short v17
) { return __add_noovfl_unsigned_short_18(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16,
  unsigned short v17,
  unsigned short v18
) { return __add_noovfl_unsigned_short_19(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned short v0,
  unsigned short v1,
  unsigned short v2,
  unsigned short v3,
  unsigned short v4,
  unsigned short v5,
  unsigned short v6,
  unsigned short v7,
  unsigned short v8,
  unsigned short v9,
  unsigned short v10,
  unsigned short v11,
  unsigned short v12,
  unsigned short v13,
  unsigned short v14,
  unsigned short v15,
  unsigned short v16,
  unsigned short v17,
  unsigned short v18,
  unsigned short v19
) { return __add_noovfl_unsigned_short_20(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18,
    v19
    );
}
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_1(
  unsigned int v0
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_2(
  unsigned int v0,
  unsigned int v1
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_3(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_4(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_5(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_6(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_7(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_8(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_9(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_10(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_11(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_12(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_13(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_14(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_15(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_16(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_17(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_18(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16,
  unsigned int v17
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_19(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16,
  unsigned int v17,
  unsigned int v18
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_int_20(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16,
  unsigned int v17,
  unsigned int v18,
  unsigned int v19
);
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0
) { return __add_noovfl_unsigned_int_1(
    v0
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1
) { return __add_noovfl_unsigned_int_2(
    v0,
    v1
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2
) { return __add_noovfl_unsigned_int_3(
    v0,
    v1,
    v2
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3
) { return __add_noovfl_unsigned_int_4(
    v0,
    v1,
    v2,
    v3
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4
) { return __add_noovfl_unsigned_int_5(
    v0,
    v1,
    v2,
    v3,
    v4
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5
) { return __add_noovfl_unsigned_int_6(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6
) { return __add_noovfl_unsigned_int_7(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7
) { return __add_noovfl_unsigned_int_8(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8
) { return __add_noovfl_unsigned_int_9(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9
) { return __add_noovfl_unsigned_int_10(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10
) { return __add_noovfl_unsigned_int_11(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11
) { return __add_noovfl_unsigned_int_12(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12
) { return __add_noovfl_unsigned_int_13(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13
) { return __add_noovfl_unsigned_int_14(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14
) { return __add_noovfl_unsigned_int_15(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15
) { return __add_noovfl_unsigned_int_16(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16
) { return __add_noovfl_unsigned_int_17(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16,
  unsigned int v17
) { return __add_noovfl_unsigned_int_18(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16,
  unsigned int v17,
  unsigned int v18
) { return __add_noovfl_unsigned_int_19(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned int v0,
  unsigned int v1,
  unsigned int v2,
  unsigned int v3,
  unsigned int v4,
  unsigned int v5,
  unsigned int v6,
  unsigned int v7,
  unsigned int v8,
  unsigned int v9,
  unsigned int v10,
  unsigned int v11,
  unsigned int v12,
  unsigned int v13,
  unsigned int v14,
  unsigned int v15,
  unsigned int v16,
  unsigned int v17,
  unsigned int v18,
  unsigned int v19
) { return __add_noovfl_unsigned_int_20(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18,
    v19
    );
}
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_1(
  unsigned long v0
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_2(
  unsigned long v0,
  unsigned long v1
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_3(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_4(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_5(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_6(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_7(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_8(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_9(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_10(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_11(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_12(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_13(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_14(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_15(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_16(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_17(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_18(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16,
  unsigned long v17
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_19(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16,
  unsigned long v17,
  unsigned long v18
);
_DEVICE_QUALIFIER bool __add_noovfl_unsigned_long_20(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16,
  unsigned long v17,
  unsigned long v18,
  unsigned long v19
);
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0
) { return __add_noovfl_unsigned_long_1(
    v0
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1
) { return __add_noovfl_unsigned_long_2(
    v0,
    v1
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2
) { return __add_noovfl_unsigned_long_3(
    v0,
    v1,
    v2
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3
) { return __add_noovfl_unsigned_long_4(
    v0,
    v1,
    v2,
    v3
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4
) { return __add_noovfl_unsigned_long_5(
    v0,
    v1,
    v2,
    v3,
    v4
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5
) { return __add_noovfl_unsigned_long_6(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6
) { return __add_noovfl_unsigned_long_7(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7
) { return __add_noovfl_unsigned_long_8(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8
) { return __add_noovfl_unsigned_long_9(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9
) { return __add_noovfl_unsigned_long_10(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10
) { return __add_noovfl_unsigned_long_11(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11
) { return __add_noovfl_unsigned_long_12(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12
) { return __add_noovfl_unsigned_long_13(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13
) { return __add_noovfl_unsigned_long_14(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14
) { return __add_noovfl_unsigned_long_15(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15
) { return __add_noovfl_unsigned_long_16(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16
) { return __add_noovfl_unsigned_long_17(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16,
  unsigned long v17
) { return __add_noovfl_unsigned_long_18(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16,
  unsigned long v17,
  unsigned long v18
) { return __add_noovfl_unsigned_long_19(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18
    );
}
_DEVICE_QUALIFIER static __attribute__((always_inline)) __attribute__((overloadable)) bool __add_noovfl(
  unsigned long v0,
  unsigned long v1,
  unsigned long v2,
  unsigned long v3,
  unsigned long v4,
  unsigned long v5,
  unsigned long v6,
  unsigned long v7,
  unsigned long v8,
  unsigned long v9,
  unsigned long v10,
  unsigned long v11,
  unsigned long v12,
  unsigned long v13,
  unsigned long v14,
  unsigned long v15,
  unsigned long v16,
  unsigned long v17,
  unsigned long v18,
  unsigned long v19
) { return __add_noovfl_unsigned_long_20(
    v0,
    v1,
    v2,
    v3,
    v4,
    v5,
    v6,
    v7,
    v8,
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15,
    v16,
    v17,
    v18,
    v19
    );
}
